version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:15-bullseye
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-network
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres?schema=public
    ports:
      - 3000:3000
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge